# Generated by Django 6.0.2 on 2026-02-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='salary_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
