# Generated by Django 6.0.2 on 2026-02-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacherprofile_salary_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-day', 'start_time']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
