# Generated by Django 6.0.2 on 2026-02-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_batch_subject_alter_lecture_options_lecture_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='batch',
            field=models.ForeignKey(choices=[('Batch A', 'Batch A'), ('Batch B', 'Batch B'), ('Batch C', 'Batch C')], default='Batch A', on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography')], default='Mathematics', on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
