# Generated by Django 6.0.2 on 2026-02-09 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lecture_batch_alter_lecture_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(choices=[('Batch A', 'Batch A'), ('Batch B', 'Batch B'), ('Batch C', 'Batch C')], default='Batch A', max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography')], default='Mathematics', max_length=100),
        ),
    ]
