# Generated by Django 6.0.2 on 2026-02-09 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_batch_name_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='core.batch'),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(to='core.subject'),
        ),
    ]
