# Generated by Django 6.0.2 on 2026-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_studentprofile_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
