# Generated by Django 6.0.2 on 2026-02-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='core.batch'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='core.subject'),
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(related_name='teachers', to='core.subject'),
        ),
    ]
