# Generated by Django 6.0.2 on 2026-02-10 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_daily_lecturres'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_lecturres',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='daily_lecturres',
            name='created_from_timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_lectures', to='core.lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(blank=True, default='Monday', max_length=10, null=True),
        ),
    ]
