from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_dashboard, name='admin_dashboard'),
    path('pending-registrations/', views.pending_registrations, name='pending_registrations'),
    path('approve-registration/<int:user_id>/', views.approve_registration, name='approve_registration'),
    path('reject-registration/<int:user_id>/', views.reject_registration, name='reject_registration'),
    path('all-students/', views.all_students, name='all_students'),
    path('edit-student/<int:user_id>/', views.edit_student, name='edit_student'),
    path('delete-student/<int:user_id>/', views.delete_student, name='delete_student'),
    path('add-student/', views.add_student, name='add_student'),
    path('complete-add-student/<int:user_id>/', views.complete_add_student, name='complete_add_student'),
    path('all-teachers/', views.all_teachers, name='all_teachers'),
    path('edit-teacher/<int:user_id>/', views.edit_teacher, name='edit_teacher'),
    path('delete-teacher/<int:user_id>/', views.delete_teacher, name='delete_teacher'),
    path('add-teacher/', views.add_teacher, name='add_teacher'),
    path('complete-add-teacher/<int:user_id>/', views.complete_add_teacher, name='complete_add_teacher'),
    path('attendance/', views.attendance_view, name='attendance_view'),
    path('approve-profile-updates/', views.approve_profile_updates, name='approve_profile_updates'),
    path('approve-student-profile/<int:profile_id>/', views.approve_student_profile_update, name='approve_student_profile_update'),
    path('reject-student-profile/<int:profile_id>/', views.reject_student_profile_update, name='reject_student_profile_update'),
    path('approve-teacher-profile/<int:profile_id>/', views.approve_teacher_profile_update, name='approve_teacher_profile_update'),
    path('reject-teacher-profile/<int:profile_id>/', views.reject_teacher_profile_update, name='reject_teacher_profile_update'),
    path('mark-notification-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('timetable/', views.manage_timetable, name='manage_timetable'),
    path('add-lecture/', views.add_lecture, name='add_lecture'),
    path('edit-lecture/<int:lecture_id>/', views.edit_lecture, name='edit_lecture'),
    path('delete-lecture/<int:lecture_id>/', views.delete_lecture, name='delete_lecture'),
    path('manage-subjects/', views.manage_subjects, name='manage_subjects'),
    path('manage-batches/', views.manage_batches, name='manage_batches'),
    path('add-subject/', views.add_subject, name='add_subject'),
    path('delete-subject/<int:subject_id>/', views.delete_subject, name='delete_subject'),
    path('add-batch/', views.add_batch, name='add_batch'),
    path('delete-batch/<int:batch_id>/', views.delete_batch, name='delete_batch'),
]
